[tool.robotpy]

# Version of robotpy this project depends on
robotpy_version = "2025.3.1.0"

robotpy_extras = [
    "apriltag",
    "cscore",
    "sim",
    # "commands2",
    # "rev",
    # "navx"
    "pathplannerlib",
    # "phoenix5"
    # "phoenix6"
    # "playingwithfusion"
    # "romi"
    # "xrp"
]

# Other pip packages to install
requires = [
     "robotpy-commands-v2==2025.1.1",
     "robotpy-rev==2025.0.2",
     "numpy",
     "photonlibpy==2025.1.1",
     "robotpy-urcl==2025.0.1",
     "black==24.1.1; platform_machine != 'roborio'",
     "coverage==7.4.1; platform_machine != 'roborio'",
     "ast-selector==0.2.0; platform_machine != 'roborio'",
     "asttokens==2.4.1; platform_machine != 'roborio'",
     "pytest-timeout==2.3.1; platform_machine != 'roborio'",
]

[tool.coverage.html]
directory = "coverage_html_report"

[tool.coverage.run]
branch = true
relative_files = true
